defaults:
  - workspace_config
  - agent: fb_ddpg
  - _self_


append_goal_to_observation: True
uncertainty: True
eval_every_steps: 1000
use_wandb: true
seed: 0
experiment: go2_Qreg
discount: 0.98
num_train_steps: 2000010
save_video: False

agent:
  batch_size: 256
  z_dim: 50
  num_inference_steps: 10000
  mix_ratio: 0.3
  sampling: True
  update_z_every_step: 100
  update_z_proba: 1.
  num_z_samples: 100
  critic_reg: true
  coef_critic_reg: 100
  epoch_repeats: 4

num_eval_episodes: 10
hydra:
  run:
    dir: ./exp_local/${agent.name}